### ISSUE TITLE
Participant events missing for listeners in SDK 3.3.0 and later.

### ISSUE THREAD

**Issue by Bill1550** [voxeet/voxeet-sdk-android#11]
For Android SDK 3.3.0 and later, when a participant is added to a conference with a conference.listen() call, the participant events are not being received by the participant that created the conference using a conference.broadcast() call, nor are the receiving particpants appearing in the broadcaster's participant list.  If the receive only participants enter the conference using the conference.join call their participant events are seen by the broadcaster and they appear on the participant list.

However, this is inconsistent with existing clients in the field using the older SDK (3.2.3 or earlier) or iOS clients.

**Comment by FabienLavocat** [comment]
Hi @Bill1550, there has been a change in [SDK 3.3.0](https://docs.dolby.io/communications-apis/changelog/2021-11-16) where the `participantAddedEvent` and `participantUpdatedEvent` events will not be sent to the participants because it would create too much load on the device and cause a slowdown.
