### ISSUE TITLE
Crash - MediaSDK.java : com.voxeet.sdk.media.MediaSDK.unlockPeerOperation

### ISSUE THREAD

**Issue by w3b-amit** [voxeet/voxeet-sdk-android#4]
**Describe the bug**
We have received one crash in VoxeetSDK on Firebase crashlytic. I am sharing its detail received.

Crash Log -
MediaSDK.java line 282
com.voxeet.sdk.media.MediaSDK.unlockPeerOperation

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean com.voxeet.sdk.media.peer.PendingPeerOperation.tryUnlock(com.voxeet.sdk.media.peer.Type, java.lang.String, com.voxeet.sdk.media.peer.SdpDescription)' on a null object reference
com.voxeet.sdk.media.MediaSDK.unlockPeerOperation

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.voxeet.sdk.media.peer.PendingPeerOperation.tryUnlock(com.voxeet.sdk.media.peer.Type, java.lang.String, com.voxeet.sdk.media.peer.SdpDescription)' on a null object reference
       at com.voxeet.sdk.media.MediaSDK.unlockPeerOperation(MediaSDK.java:282)
       at com.voxeet.sdk.media.MediaSDK.onSessionCreated(MediaSDK.java:159)

**Specifications**
 Device - Redmi 9
 OS - Android 10

**Comment by codlab** [comment]
Please update the SDK, this issue has been already fixed few version ago. Our latest is 3.1.4
